name: Push Tests

on: [push]

jobs:
  test-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm ci
      - name: Download and Build pkg-config
        run: ./build-local-pkg-config.sh
      - name: Check ESLint
        run: npx eslint .
      - name: Check Prettier
        run: npx prettier -c .
      - name: Run Tests
        run: npm run test
  test-apple-clang:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm ci
      - run: npm pack
      - name: Test Building with Apple Clang
        run: |
          cd pkg-test
          npm init -y
          npm i ../espkg-config-*.tgz
          ./test-clang.sh
  test-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm ci
      - run: npm pack
      - name: Test Building with GCC
        run: |
          cd pkg-test
          npm init -y
          npm i ../espkg-config-*.tgz
          ./test-gcc.sh
  test-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm ci
      - run: npm pack
      - name: Install espkg-config in pkg-test
        shell: bash
        run: |
          cd pkg-test
          npm init -y
          npm i ../espkg-config-*.tgz
      - name: Test Building with MSVC
        shell: cmd
        run: |
          set -e
          cd pkg-test
          "%ProgramFiles(x86)%\\Microsoft Visual Studio\\Installer\\vswhere.exe" -property resolvedInstallationPath > vsdir.txt
          set /p VS=<vsdir.txt
          call "%VS%\\VC\\Auxiliary\\Build\\vcvars64.bat"
          call .\test-msvc.bat
